name: Gradient Descent
description: A blog brought to you by experience from stupid life decisions.
meta_description: "Gradient Descent, Learning to learn"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: "/gradient-descent"
domain_name: "https://fractal2k.github.io/gradient-descent"
google_analytics: "G-9PYCKW11VT"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Sujay Rokade"

# Disqus config
disqus-shortname: "sujay"